# NumPy Practice

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
arr = np.array(
    [1,2,3])
arr



array([1, 2, 3])

In [3]:
# Create a 2-dimensional NumPy array using np.array()
array_2d = np.array([[1,2,3], 
               [4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Create a 3-dimensional NumPy array using np.array()
array_3d = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
array_3d


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
arr.shape , arr.ndim , arr.dtype, arr.size

((3,), 1, dtype('int32'), 3)

In [7]:
# Attributes of 2-dimensional array
array_2d.shape , array_2d.ndim , array_2d.dtype, array_2d.size

((2, 3), 2, dtype('int32'), 6)

In [8]:
# Attributes of 3-dimensional array
array_3d.shape , array_3d.ndim , array_3d.dtype, array_3d.size

((2, 3, 3), 3, dtype('int32'), 18)

In [9]:
# Import pandas and create a DataFrame out of one of the arrays you've created
import pandas as pd
df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])

In [10]:
# Create an array of shape (10, 2) with only ones
ones = np.ones([10,2]) 
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros([7,2,3])
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
# Create an array within a range of 0 and 100 with step 3
step = np.arange(0,100,3)
step

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [13]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10,(7,2))

array([[8, 9],
       [0, 9],
       [0, 0],
       [8, 6],
       [0, 3],
       [4, 6],
       [3, 9]])

In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rfloat = np.random.rand(3,5)
rfloat

array([[0.32803061, 0.92615161, 0.88766082, 0.74897561, 0.78906547],
       [0.94256681, 0.4633547 , 0.56410823, 0.33679961, 0.17718112],
       [0.62968008, 0.20551188, 0.63786922, 0.09237319, 0.74510557]])

In [15]:
# Set the random seed to 42
# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.seed(42)
np.random.randint(0,10,(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [16]:
#Create an array of random numbers between 1 & 10 of size (3, 7) and save it to a variable
# Find the unique numbers in the array you just created
a4= np.random.randint(1,10,(3,7))
a4

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [17]:
# Find the 0'th index of the latest array you created
a4[0][0]

9

In [18]:
# Get the first 2 rows of latest array you created
a4[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [19]:
# Get the first 2 values of the first 2 rows of the latest array
a4[:2, :2]

array([[9, 1],
       [5, 3]])

In [20]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
a5 = np.random.randint(0,10,(3,5))
ones = np.ones((3,5))

In [21]:
# Add the two arrays together
sum= a5 + ones
sum

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [22]:
#Create another array of ones of shape (5, 3)
ones_1 = np.ones((5,3))

In [23]:
# Try add the array of ones and the other most recent array together
sum = ones_1 + ones

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [24]:
# Create another array of ones of shape (3, 5)
ones_2 = np.ones((3,5))


In [25]:
# Subtract the new array of ones from the other most recent array
sum -= ones_2

In [26]:
# Multiply the ones array with the latest array
mul= ones_2 * sum

In [27]:
# Take the latest array to the power of 2 using '**'
mul ** 2

array([[36., 49.,  4.,  0.,  9.],
       [ 1., 49.,  9.,  1., 25.],
       [25., 81.,  9., 25.,  1.]])

In [28]:
# Do the same thing with np.square()
np.square(mul)

array([[36., 49.,  4.,  0.,  9.],
       [ 1., 49.,  9.,  1., 25.],
       [25., 81.,  9., 25.,  1.]])

In [29]:
# Find the mean of the latest array using np.mean()
np.mean(mul)

3.8666666666666667

In [30]:
# Find the maximum of the latest array using np.max()
np.max(mul)

9.0

In [31]:
# Find the minimum of the latest array using np.min()
np.min(mul)

0.0

In [32]:
# Find the standard deviation of the latest array
np.std(mul)

2.578543947441829

In [33]:
# Find the variance of the latest array
np.var(mul)

6.648888888888889

In [34]:
# Reshape the latest array to (3, 5, 1)
np.reshape(mul, (3,5,1))

array([[[6.],
        [7.],
        [2.],
        [0.],
        [3.]],

       [[1.],
        [7.],
        [3.],
        [1.],
        [5.]],

       [[5.],
        [9.],
        [3.],
        [5.],
        [1.]]])

In [35]:
# Transpose the latest array
mul.T

array([[6., 1., 5.],
       [7., 7., 9.],
       [2., 3., 3.],
       [0., 1., 5.],
       [3., 5., 1.]])

In [36]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random1 = np.random.randint(0, 10, (3,3))
random2 = np.random.randint(0, 10, (3,2))

In [37]:
# Perform a dot product on the two newest arrays you created
np.dot(random1, random2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [38]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random3 = np.random.randint(0, 10, (4,3))
random4 = np.random.randint(0, 10, (4,3))

In [39]:
# Perform a dot product on the two newest arrays you created
np.dot(random3, random4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [40]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(random3, random4.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

In [41]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1 = np.random.randint(0, 10, (2,2))
arr2 = np.random.randint(0, 10, (2,2))
arr1

array([[6, 6],
       [7, 4]])

In [42]:
# Compare the two arrays with '>'
arr1 > arr2

array([[ True, False],
       [ True,  True]])

In [43]:
# Compare the two arrays with '>='
arr1 >= arr2

array([[ True, False],
       [ True,  True]])

In [44]:
# Compare the two arrays with '>='
arr1 >= arr2

array([[ True, False],
       [ True,  True]])

In [45]:
# Find which elements of the first array are greater than 7
mask = arr1 > 7
arr1[mask]

array([], dtype=int32)

In [46]:
# Which parts of each array are equal? (try using '==')
mask = arr1 == arr2
arr1[mask]

array([], dtype=int32)

In [47]:
# Sort one of the arrays you just created in ascending order
np.sort(arr1)

array([[6, 6],
       [4, 7]])

In [48]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr1, axis=1)

array([[0, 1],
       [1, 0]], dtype=int64)

In [49]:
# Find the index with the maximum value in one of the arrays you've created
np.unravel_index(np.argmax(arr1), arr1.shape)

(1, 0)

In [50]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr1, axis=1)


array([0, 0], dtype=int64)

In [51]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr1, axis=0)

array([0, 1], dtype=int64)

In [52]:
# Create an array of normally distributed random numbers
normally_distribute = np.random.randn(3,4)
normally_distribute

array([[-1.03782988, -0.07580375,  0.97296353,  0.79559546],
       [ 1.49543425,  0.33818125,  3.37229625, -0.92039081],
       [-0.39863839, -0.06086409, -1.41875046,  1.04249162]])

In [53]:
# Create an array of normally distributed random numbers
normally_distribute = np.random.randn(3,4)
normally_distribute

array([[ 0.90353249,  0.01900033, -0.53441645, -1.49505387],
       [-0.78925833,  0.74371128, -0.21216142, -0.42686879],
       [ 0.50144833,  1.15818665,  0.25711687,  0.3145129 ]])

In [54]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])